# version string format -- This will be overwritten later anyway
version: "{build}"

os:
  - Visual Studio 2022

install:
  - git submodule update --init --recursive

# build with MSBuild
build:
  project: Demo/Projects/Windows/Cross++.sln        # path to Visual Studio solution or project
  parallel: true                        # enable MSBuild parallel builds
  verbosity: normal                     # MSBuild verbosity level {quiet|minimal|normal|detailed}
