name: MacOS

on:
  push:
    branches: [ "Main" ]

jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./Demo/Projects/MacOS

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Homebrew Install
      uses: tecolicom/actions-use-homebrew-tools@v1
      with:
        tools: glew glfw

    - name: Build Cross MacOS
      run: xcodebuild -scheme CrossMac build