name: Linux

on:
  push:
    branches: [ "Main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Demo/Projects/CMake

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install libglew-dev -y
        sudo apt install libglfw3-dev -y
        sudo apt install libgtk-3-dev -y

    - name: Build Project
      uses: threeal/cmake-action@v2.1.0
      with:
        source-dir: ./Demo/Projects/CMake