name: MacOS

on:
  push:
    branches: [ "Main" ]

jobs:
  build:

    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./Demo/Projects/MacOS

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Homebrew Install
      uses: tecolicom/actions-use-homebrew-tools@v1
      with:
        cache: no
        tools: glew glfw assimp

    #- name: Locate XCode
    #  uses: mxcl/xcodebuild@v2
    #  with:
    #    action: none
        #working-directory: Demo/Projects/MacOS/
        #scheme: CrossMac
        #action: build

    - name: Build Cross XCode
      run: xcodebuild -scheme CrossMac build
