name: Android

on:
  push:
    branches: [ "Main" ]

jobs:
  build:

    runs-on: ubunty-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - uses: sparkfabrik/android-build-action@v1.5.0
      with:
        project-path: Demo/Projects/MacOS/
        output-path: my-app.apk
        ruby-version: "2.7.5"
        bundler-version: "2.3.26"
        fastlane-env: "debug"
